From: Sam Spade
To: Rob Elquist
Date: 4/20/18 12:06

Superior Bicycle, Inc.

Sensitivity of this Document: CONFIDENTIAL & TRADE SECRET

Proposal: Bicycle frame design and improvements

Design Consideration: Ringing, Damping and Suspension

Lab engineers report that the oscillation frequency is within .0281 percent of their prediction. This is a significant improvement that will help us beat our competitors. 

