From: Sam Spade
To: Rob Elquist
Date: 1/20/18 08:00

Superior Bicycle, Inc.

Sensitivity of this Document: CONFIDENTIAL & TRADE SECRET

Proposal: Bicycle frame design and improvements

Design Consideration: Stiffness, Strength and Weight

The new design proposal will need to consider stiffness and weight along with strength for the new frame proposal. 

Manufactures in Taiwan are ready to adapt their factories to combining carbon with the new titaium integration developed by our labs. 