From: Sam Spade
To: Rob Elquist
Date: 4/15/18 11:11

Superior Bicycle, Inc.

Sensitivity of this Document: CONFIDENTIAL & TRADE SECRET

Proposal: Bicycle frame design and improvements

Design Consideration: Vertical stiffness

Test rider report that the prototype was good for comfort when jumping over distances of 40 feet. This exceeds our competitor’s latest product line. 

We should be able to initiate production at our Taiwan partner's factory before completing all of are tests.
