From: Sam Spade
To: Rob Elquist
Date: 2/27/18 08:04

Superior Bicycle, Inc.

Sensitivity of this Document: CONFIDENTIAL & TRADE SECRET

Proposal: Bicycle frame design and improvements

Design Consideration: Weight

By limiting the quantity of aluminum we will be able keep the frame with 10% of our goal. The lab was able to determine there is sufficient stiffness for sudden impacts from trail rides for mountain bikes.