From: Sam Spade
To: Rob Elquist
Date: 3/30/18 10:14

Superior Bicycle, Inc.

Sensitivity of this Document: CONFIDENTIAL & TRADE SECRET

Proposal: Bicycle frame design and improvements

Design Consideration: Stiffness and ride quality

The lab reports additional dampening must be designed into the headset to minimize stress on the toptube of a downhill mountain bike. 

Additional resources will be needed to further test and develop how this can be done. 